---
title: "R Notebook"
output: html_notebook
---
```{r, message = FALSE}
salaries <- read_csv("dataset/ds_salaries.csv")
# no scientific notation below 999 digits
options(scipen = 999) 
```

# Company Size versus Salary

```{r}
salaries %>%
  ggplot(aes(x = company_size, y = salary_in_usd)) +
  geom_boxplot() +
  labs(x = "Company Size", y = "Salary (USD)", title = "Comparing Company Size to Pay", subtitle = "In Data Science-Related Occupations") +
  theme_light() +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5))

salaries %>%
  group_by(company_size) %>%
  summarize(mean_pay_usd = mean(salary_in_usd),
            median_pay_usd = median(salary_in_usd),
            sd_pay_usd = sd(salary_in_usd),
            max_pay_usd = max(salary_in_usd),
            min_pay_usd = min(salary_in_usd))
```

# Country versus Salary

- Only count countries that have >= `n` employees in dataset 
- Using <https://gist.github.com/radcliff/f09c0f88344a7fcef373> to get full names of countries

```{r, message = FALSE}
country_codes <- read_csv("dataset/wikipedia-iso-country-codes.csv")

# rename the whitespaced columns with non-whitespace containing column names

country_codes %>%
  select("English short name lower case", "Alpha-2 code") %>%
  rename(eng = "English short name lower case", code = "Alpha-2 code") -> country_codes

salaries %>%
  group_by(employee_residence) %>%
  tally() %>%
  filter(n >= 5) -> country_counts

salaries %>%
  filter(employee_residence %in% country_counts$employee_residence) -> filtered_salaries

filtered_salaries %>%
  ggplot(aes(x = employee_residence, y = salary_in_usd)) -> g

x_labs <- ggplot_build(g)$layout$panel_params[[1]]$x$get_labels()
x_labs[!is.na(x_labs)] -> labels

new_labels <- c()

for(label in labels) {
  eng_name = (country_codes%>%filter(label == code))$eng
  new_labels <- c(new_labels, eng_name)
}

g+
  geom_boxplot() +
  labs(x = "Employee Residence Country", y = "Salary (USD)", title = "Comparing Employees' Residence Countries to Pay", subtitle = "In Data Science-Related Occupations") +
  theme_light() +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) +
  coord_flip() +
  scale_x_discrete(labels = new_labels)

filtered_salaries %>%
  group_by(employee_residence) %>%
  summarize(mean_pay_usd = mean(salary_in_usd),
            median_pay_usd = median(salary_in_usd),
            sd_pay_usd = sd(salary_in_usd),
            max_pay_usd = max(salary_in_usd),
            min_pay_usd = min(salary_in_usd))
```

